### ISSUE TITLE
Mark task as done

### ISSUE THREAD

**Issue by varung97** [CS2103AUG2016-T16-C3/main#10]
`done` command
Would need to be stored also - add Done TaskProperty to Tasks and in Storage

**Comment by gary-tang** [comment]
Just completed this, but there's bound to be a whole lot of issues arising from Travis CI and a drop from Coveralls (please don't tell me it's due to the parser again :).
So let's see how this goes, and I'll leave this issue open for the time being. Haha XD
See my commit for more details.

**Comment by varung97** [comment]
Done in 539286f
