### ISSUE TITLE
Design a better UI

### ISSUE THREAD

**Issue by varung97** [CS2103AUG2016-T16-C3/main#15]
Maybe have one panel showing today's tasks, and another panel showing the listed tasks and all?
How to differentiate between different types of tasks? Is there a need to differentiate?
Do we need more than 2 panels?
Redesign the task cards to display information more effectively... Venue is not as important so that could be smaller, but time should be larger
Do we want to colour code the tasks based on priority? We only have 3 levels of priority as of now... do we want to change this?

**Comment by dfz2019** [comment]
This issue is generally a place to discuss what to do next. Up to now, we decide to divide this "Design a better UI" to 2 different parts. The first part is to add a new property called "tag" to task, and then make a list of tags in the left side of the original list of tasks.
