### ISSUE TITLE
Displaying tasks with very long descriptions

### ISSUE THREAD

**Issue by varung97** [CS2103AUG2016-T16-C3/main#22]
How do we do that? Do we chop off everything after a certain number of characters and put ...? That could maybe work

**Comment by dfz2019** [comment]
Yeah or maybe we can mention the word limit in the introduction part, and then just cut off the overflow words

**Comment by varung97** [comment]
Since we need to cater to the user as much as possible, maybe we could allow up to a certain length, but not display all of it on the UI

**Comment by dfz2019** [comment]
Still don't have some ways to implement this feature.. So I do it in an alternative way, which is expanding the width of list panel to fit.
Like 6695ab3ad7d749bcc1108fe437df61e11bd56b88

**Comment by varung97** [comment]
Done in b3f4e24
