### ISSUE TITLE
Remove Browser Panel from UI

### ISSUE THREAD

**Issue by varung97** [CS2103AUG2016-T16-C3/main#23]
We're not using it so there isn't any need for it

**Comment by dfz2019** [comment]
Sure, and we have to make a list of listing different types of list.
By the way, I'm still learning the JavaFx things..quite complicated..

**Comment by varung97** [comment]
Yeah sure
We could discuss this further in #15

**Comment by dfz2019** [comment]
I have removed the browser panel, but it still looks a little ugly, will think more ways to upgrade UI.

**Comment by varung97** [comment]
Remove the Browser Panel file, as well as the commented code also please. And if there's tests for it, then that too. Additionally, think can remove the select command also, since that was just searching on the browser.

**Comment by dfz2019** [comment]
Removed the Browser Panel file. And the test cases are for ResultDisplay.java and TaskCard.java, have no impact on the existence of Browser Panel.

**Comment by varung97** [comment]
Remove Select Command also please

**Comment by dfz2019** [comment]
Removed.

**Comment by varung97** [comment]
The .java file also haha

**Comment by dfz2019** [comment]
Why is it different from my local repo, I already removed it on my local repo...
I hate Git..
Removed SelectCommand.java

**Comment by varung97** [comment]
😂 😂 awesome, thanks

**Comment by varung97** [comment]
Remove this file /src/main/java/seedu/manager/commons/events/ui/JumpToListRequestEvent.java
And method at line 114 in file /src/main/java/seedu/manager/ui/UiManager.java

**Comment by dfz2019** [comment]
What does this JumpToListRequestEvent.java do?

**Comment by varung97** [comment]
It handles the highlighting of task when it is selected using `select`. Don't think we would need that any more.

Actually, I'll remove it, I have it open in front of me.

**Comment by varung97** [comment]
Done in 38c5150
