### ISSUE TITLE
Date validation

### ISSUE THREAD

**Issue by varung97** [CS2103AUG2016-T16-C3/main#35]
From is after To, Date is before today

**Comment by varung97** [comment]
I think it would be better if the exception is thrown using an IllegalValueException.

Right now, the exception is not caught anywhere and will cause the program to crash when it is thrown (in fact, I tried it out and its not getting thrown even when start time is greater than end time - try comparing the datetime values rather than their string representations).

As an IllegalValueException, it will be handled by the code calling it, and an error message will be shown to the user (the text of the exception).

**Comment by dfz2019** [comment]
Sure, will change it. 
I know my code is quite messy..

**Comment by dfz2019** [comment]
Done in 0abb21f743a5dfdf3fa9e9ba284bd5e2ab278d15

**Comment by varung97** [comment]
Looks good 👍 
I wanted to have start time before current time is not valid, but that wouldn't work because then when we read tasks from the file, and they are overdue, then it would be invalid.
