### ISSUE TITLE
Highlight the task when user edits that task

### ISSUE THREAD

**Issue by dfz2019** [CS2103AUG2016-T16-C3/main#39]

**Comment by varung97** [comment]
See [here](https://github.com/CS2103AUG2016-T16-C3/main/commit/8e72e36772d1e23bbb632830f2b6781c8b4b1870) for how select command used jumpToList

See [here](https://github.com/CS2103AUG2016-T16-C3/main/commit/38c5150ceb57681e29834a9a9799794e134c65db) for bringing back jumpToList

**Comment by varung97** [comment]
Done in 0872548
