### ISSUE TITLE
Update User Guide to match V0.5

### ISSUE THREAD

**Issue by varung97** [CS2103AUG2016-T16-C3/main#42]

**Comment by gary-tang** [comment]
Done in f83a7b3
Please take a look 1st before closing. The UG has also been proofread by me.

**Comment by varung97** [comment]
Like that you included the commit hash 👍 
Will look at it when I get time :)

**Comment by gary-tang** [comment]
1st time lol... at least I'm throwing myself back into the game before things turn bad

**Comment by gary-tang** [comment]
Edited some of the syntax in c33b2b3
(And do pardon me for using the wrong name just now :X)

**Comment by varung97** [comment]
Wrong name?

**Comment by gary-tang** [comment]
I previously wrote "Update DeveloperGuide.md" X.X

**Comment by gary-tang** [comment]
Updated in 4bb4e8f
An appendix on supported date and time inputs will follow shortly.
Also marked up commands in the command descriptions (represented in italics)
